# Generated by Django 5.1.2 on 2024-11-04 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mood_logging", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moodlog",
            name="date",
            field=models.DateField(),
        ),
    ]
